name: Publish Docker

on:
  push:
    branches:
      - main
      - v*-branch
    tags:
      - v*
  pull_request:
    branches:
      - main
      - v*-branch

permissions:
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GHCR_BASE: ghcr.io/mistywest
  BASE_IMAGE_NAME: zephyr-base
  NRF_IMAGE_NAME: zephyr-nrf

jobs:
  build-base:
    name: Build Base Image (${{ matrix.arch }})
    runs-on: ubuntu-latest
    outputs:
      base_image_tag_amd64: ${{ steps.meta_base.outputs.version }}
      base_image_tag_arm64: ${{ steps.meta_base.outputs.version }}

    strategy:
      fail-fast: true
      matrix:
        arch: 
          - amd64
        # - arm64  # Uncomment to enable ARM64 builds

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate metadata for base image
        id: meta_base
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_BASE }}/${{ env.BASE_IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ matrix.arch }}

      - name: Build and Push Base Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile.zephyr
          tags: ${{ steps.meta_base.outputs.tags }}
          labels: ${{ steps.meta_base.outputs.labels }}
          build-args: |
            arch=${{ matrix.arch }}
            ZSDK_VERSION=0.17.0

  build-nrf:
    name: Build nRF Image (${{ matrix.sdk_nrf_branch }}, ${{ matrix.arch }})
    runs-on: ubuntu-latest
    needs: build-base  # Ensure base image is built first

    strategy:
      fail-fast: true
      matrix:
        sdk_nrf_branch:
          - v2.9.0
          - v2.8.0
        arch: 
          - amd64
        # - arm64  # Uncomment to enable ARM64 builds

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate metadata for nRF image
        id: meta_nrf
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_BASE }}/${{ env.NRF_IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ matrix.sdk_nrf_branch }}-${{ matrix.arch }}

      - name: Build and Push nRF Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile.nrf
          tags: ${{ steps.meta_nrf.outputs.tags }}
          labels: ${{ steps.meta_nrf.outputs.labels }}
          build-args: |
            arch=${{ matrix.arch }}
            BASE_IMAGE=${{ env.GHCR_BASE }}/${{ env.BASE_IMAGE_NAME }}:${{ matrix.arch }}
            sdk_nrf_branch=${{ matrix.sdk_nrf_branch }}
            toolchain_version=${{ matrix.sdk_nrf_branch }}
