name: Publish Docker

on:
  push:
    branches:
    - main
    - v*-branch
    tags:
    - v*
  pull_request:
    branches:
    - main
    - v*-branch

permissions:
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GHCR_BASE: ghcr.io/mistywest
  BASE_IMAGE_NAME: zephyr-base
  NRF_IMAGE_NAME: zephyr-nrf

jobs:
  build:
    name: Build (${{ matrix.variant.platform }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - sdk_nrf_branch: v2.9.0
            toolchain_version: v2.9.0
            ZSDK_VERSION: 0.17.0

          - sdk_nrf_branch: v2.8.0
            toolchain_version: v2.8.0
            ZSDK_VERSION: 0.17.0
        variant:
        - platform: linux/amd64
          arch: amd64
        # - platform: linux/arm64
        #   arch: arm64
        #   builder: zephyr-runner-v2-linux-arm64-4xlarge

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate metadata for base image
      id: meta_base
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.GHCR_BASE }}/${{ env.BASE_IMAGE_NAME }}
        flavor: |
          latest=false
          suffix=-${{ matrix.variant.arch }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr

    - name: Generate metadata for nRF image
      id: meta_nrf
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.GHCR_BASE }}/${{ env.NRF_IMAGE_NAME }}
        flavor: |
          latest=false
          suffix=-${{ matrix.variant.arch }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr

    - name: Build base image
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        file: Dockerfile.zephyr
        tags: ${{ steps.meta_base.outputs.tags }}
        labels: ${{ steps.meta_base.outputs.labels }}
        build-args: |
          ZSDK_VERSION=${{ matrix.ZSDK_VERSION }}

    - name: Build nRF image
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        file: Dockerfile.nrf
        tags: ${{ steps.meta_nrf.outputs.tags }}
        labels: ${{ steps.meta_nrf.outputs.labels }}
        build-args: |
          BASE_IMAGE=${{ env.GHCR_BASE }}/${{ env.BASE_IMAGE_NAME }}:${{ steps.meta_base.outputs.version }}
          sdk_nrf_branch=${{ matrix.sdk_nrf_branch }}
          toolchain_version=${{ matrix.toolchain_version }}
